# Generated by Django 3.2.6 on 2021-09-01 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='file code'),
        ),
    ]
