# Generated by Django 3.2.6 on 2021-09-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_alter_content_file_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatas', to='entertainment.content'),
        ),
    ]
