# Generated by Django 3.2.6 on 2021-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_alter_channel_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='channels_by_group', to='entertainment.Group', verbose_name='groups'),
        ),
    ]
